//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Nombre de archivo original:
// Fecha de generación: 23/04/2021 13:36:04
namespace ClimaWS.DataAccess
{
    
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.Clima en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdClima
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="Clima")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Clima : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Clima.
        /// </summary>
        /// <param name="idClima">Valor inicial de IdClima.</param>
        /// <param name="fechaCreacion">Valor inicial de FechaCreacion.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Clima CreateClima(decimal idClima, global::System.DateTime fechaCreacion)
        {
            Clima clima = new Clima();
            clima.IdClima = idClima;
            clima.FechaCreacion = fechaCreacion;
            return clima;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdClima en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdClima
        {
            get
            {
                return this._IdClima;
            }
            set
            {
                this.OnIdClimaChanging(value);
                this.ReportPropertyChanging("IdClima");
                this._IdClima = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdClima");
                this.OnIdClimaChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdClima;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdClimaChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdClimaChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad grados en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string grados
        {
            get
            {
                return this._grados;
            }
            set
            {
                this.OngradosChanging(value);
                this.ReportPropertyChanging("grados");
                this._grados = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("grados");
                this.OngradosChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _grados;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OngradosChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OngradosChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdCiudad en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> IdCiudad
        {
            get
            {
                return this._IdCiudad;
            }
            set
            {
                this.OnIdCiudadChanging(value);
                this.ReportPropertyChanging("IdCiudad");
                this._IdCiudad = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdCiudad");
                this.OnIdCiudadChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _IdCiudad;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdCiudadChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdCiudadChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdEstado en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> IdEstado
        {
            get
            {
                return this._IdEstado;
            }
            set
            {
                this.OnIdEstadoChanging(value);
                this.ReportPropertyChanging("IdEstado");
                this._IdEstado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdEstado");
                this.OnIdEstadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _IdEstado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdEstadoChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdEstadoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.DateTime FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.DateTime _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.DateTime value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UsuarioCreacion
        {
            get
            {
                return this._UsuarioCreacion;
            }
            set
            {
                this.OnUsuarioCreacionChanging(value);
                this.ReportPropertyChanging("UsuarioCreacion");
                this._UsuarioCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UsuarioCreacion");
                this.OnUsuarioCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UsuarioCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.EstadoClima en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdEstado
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="EstadoClima")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class EstadoClima : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto EstadoClima.
        /// </summary>
        /// <param name="idEstado">Valor inicial de IdEstado.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static EstadoClima CreateEstadoClima(decimal idEstado)
        {
            EstadoClima estadoClima = new EstadoClima();
            estadoClima.IdEstado = idEstado;
            return estadoClima;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdEstado en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdEstado
        {
            get
            {
                return this._IdEstado;
            }
            set
            {
                this.OnIdEstadoChanging(value);
                this.ReportPropertyChanging("IdEstado");
                this._IdEstado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdEstado");
                this.OnIdEstadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdEstado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdEstadoChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdEstadoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UsuarioCreacion
        {
            get
            {
                return this._UsuarioCreacion;
            }
            set
            {
                this.OnUsuarioCreacionChanging(value);
                this.ReportPropertyChanging("UsuarioCreacion");
                this._UsuarioCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UsuarioCreacion");
                this.OnUsuarioCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UsuarioCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.Roles en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdRol
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="Roles")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Roles : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Roles.
        /// </summary>
        /// <param name="idRol">Valor inicial de IdRol.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Roles CreateRoles(decimal idRol)
        {
            Roles roles = new Roles();
            roles.IdRol = idRol;
            return roles;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdRol en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdRol
        {
            get
            {
                return this._IdRol;
            }
            set
            {
                this.OnIdRolChanging(value);
                this.ReportPropertyChanging("IdRol");
                this._IdRol = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdRol");
                this.OnIdRolChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdRol;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdRolChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdRolChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Descripcion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Descripcion
        {
            get
            {
                return this._Descripcion;
            }
            set
            {
                this.OnDescripcionChanging(value);
                this.ReportPropertyChanging("Descripcion");
                this._Descripcion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Descripcion");
                this.OnDescripcionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Descripcion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDescripcionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnDescripcionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UsuarioCreacion
        {
            get
            {
                return this._UsuarioCreacion;
            }
            set
            {
                this.OnUsuarioCreacionChanging(value);
                this.ReportPropertyChanging("UsuarioCreacion");
                this._UsuarioCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UsuarioCreacion");
                this.OnUsuarioCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UsuarioCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.Usuarios en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdUsuario
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="Usuarios")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Usuarios : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Usuarios.
        /// </summary>
        /// <param name="idUsuario">Valor inicial de IdUsuario.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Usuarios CreateUsuarios(decimal idUsuario)
        {
            Usuarios usuarios = new Usuarios();
            usuarios.IdUsuario = idUsuario;
            return usuarios;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdUsuario en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdUsuario
        {
            get
            {
                return this._IdUsuario;
            }
            set
            {
                this.OnIdUsuarioChanging(value);
                this.ReportPropertyChanging("IdUsuario");
                this._IdUsuario = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdUsuario");
                this.OnIdUsuarioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdUsuario;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdUsuarioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Usuario en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Usuario
        {
            get
            {
                return this._Usuario;
            }
            set
            {
                this.OnUsuarioChanging(value);
                this.ReportPropertyChanging("Usuario");
                this._Usuario = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Usuario");
                this.OnUsuarioChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Usuario;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Password en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Password;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPasswordChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPasswordChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdRol en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> IdRol
        {
            get
            {
                return this._IdRol;
            }
            set
            {
                this.OnIdRolChanging(value);
                this.ReportPropertyChanging("IdRol");
                this._IdRol = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdRol");
                this.OnIdRolChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _IdRol;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdRolChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdRolChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Estado en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> Estado
        {
            get
            {
                return this._Estado;
            }
            set
            {
                this.OnEstadoChanging(value);
                this.ReportPropertyChanging("Estado");
                this._Estado = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Estado");
                this.OnEstadoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _Estado;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEstadoChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnEstadoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Login en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<bool> Login
        {
            get
            {
                return this._Login;
            }
            set
            {
                this.OnLoginChanging(value);
                this.ReportPropertyChanging("Login");
                this._Login = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Login");
                this.OnLoginChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<bool> _Login;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLoginChanging(global::System.Nullable<bool> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLoginChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.Ciudades en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdPais
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="Ciudades")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Ciudades : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Ciudades.
        /// </summary>
        /// <param name="idPais">Valor inicial de IdPais.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Ciudades CreateCiudades(decimal idPais)
        {
            Ciudades ciudades = new Ciudades();
            ciudades.IdPais = idPais;
            return ciudades;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdPais en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdPais
        {
            get
            {
                return this._IdPais;
            }
            set
            {
                this.OnIdPaisChanging(value);
                this.ReportPropertyChanging("IdPais");
                this._IdPais = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPais");
                this.OnIdPaisChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdPais;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdPaisChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdPaisChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdDepartamento en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> IdDepartamento
        {
            get
            {
                return this._IdDepartamento;
            }
            set
            {
                this.OnIdDepartamentoChanging(value);
                this.ReportPropertyChanging("IdDepartamento");
                this._IdDepartamento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdDepartamento");
                this.OnIdDepartamentoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _IdDepartamento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdDepartamentoChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdDepartamentoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UsuarioCreacion
        {
            get
            {
                return this._UsuarioCreacion;
            }
            set
            {
                this.OnUsuarioCreacionChanging(value);
                this.ReportPropertyChanging("UsuarioCreacion");
                this._UsuarioCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UsuarioCreacion");
                this.OnUsuarioCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UsuarioCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.Departamentos en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdDepartamento
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="Departamentos")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Departamentos : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Departamentos.
        /// </summary>
        /// <param name="idDepartamento">Valor inicial de IdDepartamento.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Departamentos CreateDepartamentos(decimal idDepartamento)
        {
            Departamentos departamentos = new Departamentos();
            departamentos.IdDepartamento = idDepartamento;
            return departamentos;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdDepartamento en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdDepartamento
        {
            get
            {
                return this._IdDepartamento;
            }
            set
            {
                this.OnIdDepartamentoChanging(value);
                this.ReportPropertyChanging("IdDepartamento");
                this._IdDepartamento = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdDepartamento");
                this.OnIdDepartamentoChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdDepartamento;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdDepartamentoChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdDepartamentoChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad IdPais en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<decimal> IdPais
        {
            get
            {
                return this._IdPais;
            }
            set
            {
                this.OnIdPaisChanging(value);
                this.ReportPropertyChanging("IdPais");
                this._IdPais = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPais");
                this.OnIdPaisChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<decimal> _IdPais;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdPaisChanging(global::System.Nullable<decimal> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdPaisChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UsuarioCreacion
        {
            get
            {
                return this._UsuarioCreacion;
            }
            set
            {
                this.OnUsuarioCreacionChanging(value);
                this.ReportPropertyChanging("UsuarioCreacion");
                this._UsuarioCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UsuarioCreacion");
                this.OnUsuarioCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UsuarioCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppModel.Pais en el esquema.
    /// </summary>
    /// <KeyProperties>
    /// IdPais
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="ClimaWebAppModel", Name="Pais")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Pais : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Crear un nuevo objeto Pais.
        /// </summary>
        /// <param name="idPais">Valor inicial de IdPais.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Pais CreatePais(decimal idPais)
        {
            Pais pais = new Pais();
            pais.IdPais = idPais;
            return pais;
        }
        /// <summary>
        /// No hay ningún comentario para la propiedad IdPais en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public decimal IdPais
        {
            get
            {
                return this._IdPais;
            }
            set
            {
                this.OnIdPaisChanging(value);
                this.ReportPropertyChanging("IdPais");
                this._IdPais = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IdPais");
                this.OnIdPaisChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private decimal _IdPais;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdPaisChanging(decimal value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdPaisChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad Nombre en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Nombre
        {
            get
            {
                return this._Nombre;
            }
            set
            {
                this.OnNombreChanging(value);
                this.ReportPropertyChanging("Nombre");
                this._Nombre = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Nombre");
                this.OnNombreChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Nombre;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNombreChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad UsuarioCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string UsuarioCreacion
        {
            get
            {
                return this._UsuarioCreacion;
            }
            set
            {
                this.OnUsuarioCreacionChanging(value);
                this.ReportPropertyChanging("UsuarioCreacion");
                this._UsuarioCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("UsuarioCreacion");
                this.OnUsuarioCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _UsuarioCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnUsuarioCreacionChanged();
        /// <summary>
        /// No hay ningún comentario para la propiedad FechaCreacion en el esquema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<global::System.DateTime> FechaCreacion
        {
            get
            {
                return this._FechaCreacion;
            }
            set
            {
                this.OnFechaCreacionChanging(value);
                this.ReportPropertyChanging("FechaCreacion");
                this._FechaCreacion = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("FechaCreacion");
                this.OnFechaCreacionChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<global::System.DateTime> _FechaCreacion;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanging(global::System.Nullable<global::System.DateTime> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnFechaCreacionChanged();
    }
    /// <summary>
    /// No hay ningún comentario para ClimaWebAppEntities en el esquema.
    /// </summary>
    public partial class ClimaWebAppEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Inicializa un nuevo objeto ClimaWebAppEntities usando la cadena de conexión encontrada en la sección 'ClimaWebAppEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ClimaWebAppEntities() : 
                base("name=ClimaWebAppEntities", "ClimaWebAppEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto ClimaWebAppEntities.
        /// </summary>
        public ClimaWebAppEntities(string connectionString) : 
                base(connectionString, "ClimaWebAppEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Inicializar un nuevo objeto ClimaWebAppEntities.
        /// </summary>
        public ClimaWebAppEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "ClimaWebAppEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// No hay ningún comentario para Clima en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Clima> Clima
        {
            get
            {
                if ((this._Clima == null))
                {
                    this._Clima = base.CreateQuery<Clima>("[Clima]");
                }
                return this._Clima;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Clima> _Clima;
        /// <summary>
        /// No hay ningún comentario para EstadoClima en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<EstadoClima> EstadoClima
        {
            get
            {
                if ((this._EstadoClima == null))
                {
                    this._EstadoClima = base.CreateQuery<EstadoClima>("[EstadoClima]");
                }
                return this._EstadoClima;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<EstadoClima> _EstadoClima;
        /// <summary>
        /// No hay ningún comentario para Roles en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Roles> Roles
        {
            get
            {
                if ((this._Roles == null))
                {
                    this._Roles = base.CreateQuery<Roles>("[Roles]");
                }
                return this._Roles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Roles> _Roles;
        /// <summary>
        /// No hay ningún comentario para Usuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Usuarios> Usuarios
        {
            get
            {
                if ((this._Usuarios == null))
                {
                    this._Usuarios = base.CreateQuery<Usuarios>("[Usuarios]");
                }
                return this._Usuarios;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Usuarios> _Usuarios;
        /// <summary>
        /// No hay ningún comentario para Ciudades en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Ciudades> Ciudades
        {
            get
            {
                if ((this._Ciudades == null))
                {
                    this._Ciudades = base.CreateQuery<Ciudades>("[Ciudades]");
                }
                return this._Ciudades;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Ciudades> _Ciudades;
        /// <summary>
        /// No hay ningún comentario para Departamentos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Departamentos> Departamentos
        {
            get
            {
                if ((this._Departamentos == null))
                {
                    this._Departamentos = base.CreateQuery<Departamentos>("[Departamentos]");
                }
                return this._Departamentos;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Departamentos> _Departamentos;
        /// <summary>
        /// No hay ningún comentario para Pais en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Pais> Pais
        {
            get
            {
                if ((this._Pais == null))
                {
                    this._Pais = base.CreateQuery<Pais>("[Pais]");
                }
                return this._Pais;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Pais> _Pais;
        /// <summary>
        /// No hay ningún comentario para Clima en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToClima(Clima clima)
        {
            base.AddObject("Clima", clima);
        }
        /// <summary>
        /// No hay ningún comentario para EstadoClima en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToEstadoClima(EstadoClima estadoClima)
        {
            base.AddObject("EstadoClima", estadoClima);
        }
        /// <summary>
        /// No hay ningún comentario para Roles en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRoles(Roles roles)
        {
            base.AddObject("Roles", roles);
        }
        /// <summary>
        /// No hay ningún comentario para Usuarios en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToUsuarios(Usuarios usuarios)
        {
            base.AddObject("Usuarios", usuarios);
        }
        /// <summary>
        /// No hay ningún comentario para Ciudades en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToCiudades(Ciudades ciudades)
        {
            base.AddObject("Ciudades", ciudades);
        }
        /// <summary>
        /// No hay ningún comentario para Departamentos en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToDepartamentos(Departamentos departamentos)
        {
            base.AddObject("Departamentos", departamentos);
        }
        /// <summary>
        /// No hay ningún comentario para Pais en el esquema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToPais(Pais pais)
        {
            base.AddObject("Pais", pais);
        }
    }
}
