//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClimaWS.Webclima.WSClima {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSClima.WSClimaSoap")]
    public interface WSClimaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarClima", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InsertarClima(string grados, int ciudad, int estado, string user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarClima", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ActualizarClima(int IdClima, string grados, int ciudad, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/strConsultaClima", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string strConsultaClima();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/dtConsultaClima", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable dtConsultaClima();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarClima", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string EliminarClima(int IdClima);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSClimaSoapChannel : ClimaWS.Webclima.WSClima.WSClimaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSClimaSoapClient : System.ServiceModel.ClientBase<ClimaWS.Webclima.WSClima.WSClimaSoap>, ClimaWS.Webclima.WSClima.WSClimaSoap {
        
        public WSClimaSoapClient() {
        }
        
        public WSClimaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSClimaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClimaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSClimaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string InsertarClima(string grados, int ciudad, int estado, string user) {
            return base.Channel.InsertarClima(grados, ciudad, estado, user);
        }
        
        public string ActualizarClima(int IdClima, string grados, int ciudad, int estado) {
            return base.Channel.ActualizarClima(IdClima, grados, ciudad, estado);
        }
        
        public string strConsultaClima() {
            return base.Channel.strConsultaClima();
        }
        
        public System.Data.DataTable dtConsultaClima() {
            return base.Channel.dtConsultaClima();
        }
        
        public string EliminarClima(int IdClima) {
            return base.Channel.EliminarClima(IdClima);
        }
    }
}
